site_name: NINJAR-lite
site_url: https://embeddedboys.github.io/NINJAR-lite/
site_description: offical site of NINJAR-lite
site_author: embeddedboys

repo_url: https://github.com/embeddedboys/NINJAR-lite
theme:
  name: null
  custom_dir: 'cinder'
  locale: en

nav:
    - Home: README.md
    - Get Started: getstarted.md
    - Documentations:
      - 'hardware': hardware/index.md
      - 'software': software/index.md
    - About:
        - 'Credits': credits.md
        - 'License': license.md
        - 'Release Notes': releasenote.md
        - 'FAQs': FAQs.md
    - Thanks: thanks.md