site_name: NINJAR-lite
site_url: https://embeddedboys.github.io/NINJAR-lite/
site_description: offical site of NINJAR-lite
site_author: embeddedboys

repo_url: https://github.com/embeddedboys/NINJAR-lite
theme:
  name: null
  custom_dir: 'cinder'
  locale: en

nav:
    - 主页: README.md
    - 快速上手: getstarted.md
    - 文档:
      - '硬件': hardware/index.md
      - '软件': software/index.md
      - '开发记录' : dev.md
    - 关于:
        - 'Credits': credits.md
        - '许可证': license.md
        - '更新说明': releasenote.md
        - 'FAQs': FAQs.md
    - 致谢: thanks.md